#!/bin/bash
# session-capture.sh — Vault OS v4 (D2: capture is a hook with a skill on top)
# vault-os-hook-version: 4.1.0
# Fires at SessionEnd (clean exits only — does NOT fire on VS Code tab close).
#
# Reliability tiers (D2):
#   1. THIS hook writes a minimal machine record when it fires.
#   2. /capture enriches with narrative when invoked — optional, never load-bearing.
#   3. DERIVED orientation (session-orient.sh) is the safety net — git is the record of last resort.
# This hook must not clobber a richer /capture record written the same day (same-day marker check).

# ── Selftest: verify this hook's own dependencies, loudly ─────────────────────
if [ "${1:-}" = "--selftest" ]; then
  SELFTEST_FAIL=0

  if TODAY_CHECK=$(date +%Y-%m-%d 2>/dev/null) && [ -n "$TODAY_CHECK" ] \
     && TIME_CHECK=$(date +%H:%M 2>/dev/null) && [ -n "$TIME_CHECK" ]; then
    echo "PASS: date +%Y-%m-%d / +%H:%M format (${TODAY_CHECK} ${TIME_CHECK})"
  else
    echo "FAIL: date +%Y-%m-%d or +%H:%M produced no output — cannot stamp session record"
    SELFTEST_FAIL=1
  fi

  if printf 'Source: auto-generated by session-capture.sh\n' \
       | grep -q 'auto-generated by session-capture.sh'; then
    echo "PASS: grep -q works — same-day/self-stub detection available"
  else
    echo "FAIL: grep -q did not match expected sample — skip-overwrite check unavailable"
    SELFTEST_FAIL=1
  fi

  if command -v git >/dev/null 2>&1; then
    echo "PASS: git is on PATH ($(git --version 2>/dev/null)) — files-touched approximation available"
  else
    echo "WARN: git not on PATH — files-touched list will be empty (record still written)"
  fi

  SELFTEST_VAULT="${CLAUDE_PROJECT_DIR:-$PWD}"
  if [ -d "$SELFTEST_VAULT" ] && { [ -d "$SELFTEST_VAULT/ops" ] || [ -w "$SELFTEST_VAULT" ]; }; then
    echo "PASS: $SELFTEST_VAULT/ops/sessions write target has a reachable parent"
  else
    echo "FAIL: $SELFTEST_VAULT is not reachable/writable — cannot write last-active.md"
    SELFTEST_FAIL=1
  fi

  if [ "$SELFTEST_FAIL" -eq 0 ]; then
    echo "SELFTEST: all checks passed"
    exit 0
  else
    echo "SELFTEST: one or more checks failed"
    exit 1
  fi
fi

VAULT="${CLAUDE_PROJECT_DIR:?ERROR: CLAUDE_PROJECT_DIR not set — hook must be invoked by Claude Code}"
mkdir -p "$VAULT/ops/sessions"

LAST="$VAULT/ops/sessions/last-active.md"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)
SELF_MARK="auto-generated by session-capture.sh"

# Same-day marker check: if a record dated today already exists and it is NOT this hook's own
# stub, a richer /capture record was written this session — preserve it, do not clobber.
if [ -f "$LAST" ] \
   && grep -q "^Date: ${DATE}" "$LAST" 2>/dev/null \
   && ! grep -q "$SELF_MARK" "$LAST" 2>/dev/null; then
  exit 0
fi

# Files touched — APPROXIMATION. SessionEnd cannot diff against session start (no start snapshot
# is available to the hook), so we approximate with the current uncommitted working-tree changes
# plus the files in today's most recent commit. This over-counts (pre-existing dirty files) and
# under-counts (changes already committed on an earlier day). /capture gives the accurate story.
BRANCH="(not a git repo)"
FILES=""
if command -v git >/dev/null 2>&1 && git -C "$VAULT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  BRANCH=$(git -C "$VAULT" rev-parse --abbrev-ref HEAD 2>/dev/null)
  DIRTY=$(git -C "$VAULT" status --porcelain 2>/dev/null | awk '{print $NF}')
  TODAY_COMMIT=""
  if git -C "$VAULT" rev-parse HEAD >/dev/null 2>&1; then
    LAST_COMMIT_DATE=$(git -C "$VAULT" log -1 --format=%cd --date=format:%Y-%m-%d 2>/dev/null)
    if [ "$LAST_COMMIT_DATE" = "$DATE" ]; then
      TODAY_COMMIT=$(git -C "$VAULT" show --name-only --format= HEAD 2>/dev/null)
    fi
  fi
  FILES=$(printf '%s\n%s\n' "$DIRTY" "$TODAY_COMMIT" | grep -v '^$' | sort -u)
fi

{
  echo "Date: ${DATE} ${TIME}"
  echo "Branch: ${BRANCH:-<unknown>}"
  echo "Source: ${SELF_MARK} (SessionEnd hook — clean exit only; does NOT fire on VS Code tab close)"
  echo ""
  echo "Files touched (approximation — see note):"
  if [ -n "$FILES" ]; then
    echo "$FILES" | sed 's/^/  - /'
  else
    echo "  (none detected — clean tree, or not a git repo)"
  fi
  echo ""
  echo "Note: SessionEnd cannot diff against session start. The list above is uncommitted"
  echo "working-tree changes plus files in today's most recent commit — an approximation, not"
  echo "a session diff. Run /capture for a narrative summary of what was actually done and why."
} > "$LAST"
